# Generated by Django 5.1 on 2024-08-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netdevice',
            name='serial',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
